package UI;

import dataBase.dataQuery;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.ش
 */
/**
 *
 * @author Badr-Alfwazi
 */
public class CrudEm extends javax.swing.JFrame {

    private int id = 0;
    private dataQuery data = new dataQuery();

    /**
     * Creates new form CrudSt
     *
     * @param id
     */

    public void setId(int id) {
        this.id = id;
        ResultSet rs = getData(id);
        try {
            while (rs.next()) {
                fileId.setText(rs.getString("eid"));
                firstName.setText(rs.getString("Efname"));
                fatherName.setText(rs.getString("Efaname"));
                familyName.setText(rs.getString("Elname"));
                Date date = rs.getDate("Ebirthdte");
                if (date != null) {
                    birthDate.setText(date.toString());
                }
                countryLocation.setText(rs.getString("Ecountry"));
                cityVal.setText(rs.getString("Ecity"));
                jobTitle.setText(rs.getString("Stateemployee"));
                nationalityVal.setText(rs.getString("Enantionaly"));
                mobile.setText(rs.getString("TEL"));
                addressVal.setText((rs.getString("Eaddress")));
                if (rs.getString("Egender").equals("ذكر")) {
                    male.setSelected(true);
                } else {
                    female.setSelected(true);
                }
                male.setSelected(rootPaneCheckingEnabled);
            }
        } catch (SQLException ex) {
            Logger.getLogger(CrudEm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public ResultSet getData(int id) {
        ResultSet result = data.getEmployee(id);
        return result;
    }

    public CrudEm() {
        initComponents();
        setDefaultCloseOperation(this.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        maleOrfemale = new javax.swing.ButtonGroup();
        jPanel4 = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        firstName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        familyName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        fatherName = new javax.swing.JTextField();
        fileId = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        submitButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        cityVal = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        countryLocation = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jobTitle = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        addressVal = new javax.swing.JTextArea();
        nationalityVal = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        mobile = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        birthDate = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        deleteFile = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        addressVal1 = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        HometelVal1 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        nationalityVal2 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        nationalityVal3 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel4.setBackground(new java.awt.Color(0, 102, 204));
        jPanel4.setLayout(null);

        Title.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        Title.setForeground(new java.awt.Color(255, 255, 255));
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("ملف الموظف");
        jPanel4.add(Title);
        Title.setBounds(690, 30, 200, 30);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(0, 0, 914, 70);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("الأسم الأول");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, -1, -1));

        jLabel2.setBackground(new java.awt.Color(0, 102, 204));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("صورة الموظف");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 90, 120, -1));

        firstName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        firstName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        firstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameActionPerformed(evt);
            }
        });
        jPanel1.add(firstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, 144, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("اسم الأب ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, -1, -1));

        familyName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        familyName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        familyName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                familyNameActionPerformed(evt);
            }
        });
        jPanel1.add(familyName, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 129, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("اسم العائلة");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, -1, -1));

        fatherName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fatherName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        fatherName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fatherNameActionPerformed(evt);
            }
        });
        jPanel1.add(fatherName, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 129, 30));

        fileId.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fileId.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        fileId.setEnabled(false);
        fileId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileIdActionPerformed(evt);
            }
        });
        jPanel1.add(fileId, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 80, 129, 30));

        jButton3.setBackground(new java.awt.Color(204, 204, 204));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setText("رجوع");
        jButton3.setBorder(null);
        jButton3.setMaximumSize(new java.awt.Dimension(71, 31));
        jButton3.setMinimumSize(new java.awt.Dimension(71, 31));
        jButton3.setPreferredSize(new java.awt.Dimension(71, 31));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 520, 70, 30));

        submitButton.setBackground(new java.awt.Color(0, 102, 204));
        submitButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        submitButton.setForeground(new java.awt.Color(255, 255, 255));
        submitButton.setText("تحديث");
        submitButton.setBorder(null);
        submitButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });
        jPanel1.add(submitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 520, 90, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("تاريخ الميلاد");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 140, -1, -1));

        cityVal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cityVal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        cityVal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityValActionPerformed(evt);
            }
        });
        jPanel1.add(cityVal, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 127, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("بلد الإقامة");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, -1, -1));

        countryLocation.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        countryLocation.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel1.add(countryLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, 127, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("الوظيفة");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 80, -1));

        jobTitle.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jobTitle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel1.add(jobTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 127, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("العنوان");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 440, 50, -1));

        addressVal.setColumns(20);
        addressVal.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        addressVal.setLineWrap(true);
        addressVal.setRows(5);
        addressVal.setText("\n");
        addressVal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        addressVal.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane1.setViewportView(addressVal);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 410, 264, 73));

        nationalityVal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nationalityVal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel1.add(nationalityVal, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 270, 127, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("الجنسية");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 240, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("الجنس");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, -1, -1));

        maleOrfemale.add(male);
        male.setText("ذكر");
        jPanel1.add(male, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 280, -1, -1));

        maleOrfemale.add(female);
        female.setText("انثى");
        female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleActionPerformed(evt);
            }
        });
        jPanel1.add(female, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 280, -1, -1));

        mobile.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        mobile.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        mobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobileActionPerformed(evt);
            }
        });
        jPanel1.add(mobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 127, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("رقم الجوال");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 100, -1));

        birthDate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        birthDate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel1.add(birthDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 170, 127, 30));

        jLabel12.setBackground(new java.awt.Color(0, 0, 0));
        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 0, 0));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("رقم الموظف");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 50, 80, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("المدينة");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, -1, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/studentImage.jpg"))); // NOI18N
        jLabel16.setText(".");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 120, 180, 200));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 910, 10));

        deleteFile.setBackground(new java.awt.Color(255, 0, 0));
        deleteFile.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        deleteFile.setText("حذف");
        deleteFile.setBorder(null);
        deleteFile.setMaximumSize(new java.awt.Dimension(71, 31));
        deleteFile.setMinimumSize(new java.awt.Dimension(71, 31));
        deleteFile.setPreferredSize(new java.awt.Dimension(71, 31));
        deleteFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteFileActionPerformed(evt);
            }
        });
        jPanel1.add(deleteFile, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 520, 70, 30));

        addressVal1.setColumns(20);
        addressVal1.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        addressVal1.setLineWrap(true);
        addressVal1.setRows(5);
        addressVal1.setText("\n");
        addressVal1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        addressVal1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane2.setViewportView(addressVal1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 264, 73));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("ملاحظات");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 440, 70, -1));

        HometelVal1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        HometelVal1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        HometelVal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HometelVal1ActionPerformed(evt);
            }
        });
        jPanel1.add(HometelVal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 127, 30));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("رقم المنزل");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 100, -1));

        nationalityVal2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nationalityVal2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel1.add(nationalityVal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 360, 127, 30));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("الشهادة");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 330, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("الحالة الإجتماعية");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 330, -1, -1));

        nationalityVal3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nationalityVal3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel1.add(nationalityVal3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 360, 127, 30));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 73, 914, 570);

        setSize(new java.awt.Dimension(930, 683));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_femaleActionPerformed

    private void fileIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fileIdActionPerformed

    private void fatherNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fatherNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fatherNameActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        String fname = firstName.getText();
        String faname = fatherName.getText();
        String famname = familyName.getText();
        String country = countryLocation.getText();
        String city = cityVal.getText();
        String address = addressVal.getText();
        String Hometel = HometelVal1.getText();
        String Mobile = mobile.getText();
        String job = jobTitle.getName();
        if (id > 0) {
            System.out.println("CrudEm Update");
            int result = 0;
            result = data.updateQuery("UPDATE employees SET Efname = '" + fname + "',Efaname = '" + faname + "',Elname= '" + famname + "', Ecountry = '" + country + "'   , Ecity = '" + city + "' , Eaddress = '" + address + "' , Mobile = '" + Mobile + "' ,Stateemployee = '" + job + "',Tel = '"+Hometel+"'  WHERE eid = '" + id + "';");
            System.out.println("UPDATE employees SET Efname = '" + fname + "',Efaname = '" + faname + "',Elname= '" + famname + "', Ecountry = '" + country + "'   , Ecity = '" + city + "' , Eaddress = '" + address + "' , Mobile = '" + Mobile + "' ,Stateemployee = '" + job + "',Tel = '"+Hometel+"'  WHERE eid = " + id + ";");
            if (result > 0) {
                JOptionPane.showMessageDialog(this, "تم التحديث بنجاح");
            } else {
                JOptionPane.showMessageDialog(this, "حدث خطا", "خطا",
                        JOptionPane.ERROR_MESSAGE);
            }
        }


    }//GEN-LAST:event_submitButtonActionPerformed

    private void deleteFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteFileActionPerformed
        String fname = firstName.getText();
        String faname = fatherName.getText();
        String famname = familyName.getText();
        String country = countryLocation.getText();
        boolean result = false;
        try {
            result = data.insertQuery("insert INTO users (fname,faname,lname) VALUES ('" + fname + "','" + faname + "','" + famname + "')");
        } catch (Exception ex) {
            Logger.getLogger(CrudEm.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (result) {
            JOptionPane.showMessageDialog(this, "تم التحديث بنجاح");
        } else {
            JOptionPane.showMessageDialog(this, "حدث خطا", "خطا",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_deleteFileActionPerformed

    private void firstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameActionPerformed

    private void cityValActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityValActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cityValActionPerformed

    private void familyNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_familyNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_familyNameActionPerformed

    private void mobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mobileActionPerformed

    private void HometelVal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HometelVal1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HometelVal1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrudEm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrudEm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrudEm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrudEm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrudEm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField HometelVal1;
    private javax.swing.JLabel Title;
    private javax.swing.JTextArea addressVal;
    private javax.swing.JTextArea addressVal1;
    private javax.swing.JTextField birthDate;
    private javax.swing.JTextField cityVal;
    private javax.swing.JTextField countryLocation;
    private javax.swing.JButton deleteFile;
    private javax.swing.JTextField familyName;
    private javax.swing.JTextField fatherName;
    private javax.swing.JRadioButton female;
    private javax.swing.JTextField fileId;
    private javax.swing.JTextField firstName;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jobTitle;
    private javax.swing.JRadioButton male;
    private javax.swing.ButtonGroup maleOrfemale;
    private javax.swing.JTextField mobile;
    private javax.swing.JTextField nationalityVal;
    private javax.swing.JTextField nationalityVal2;
    private javax.swing.JTextField nationalityVal3;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}
