package UI;

import dataBase.dataQuery;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Badr-Alfwazi
 */
public class CrudSt extends javax.swing.JFrame {
        private int id = 0;
        private int result=0;
        private dataQuery data = new dataQuery();
    /**
     * Creates new form CrudSt
     * @param id
     */
    public void setId(int id) throws Exception  {
    submitButton.setVisible(true);
    newRecord.setVisible(false);
       this.id=id;
       ResultSet rs = getData(id);
            try {
                while (rs.next()) {
                        fileId.setText(rs.getString("sid"));
                        firstName.setText(rs.getString("fname"));
                        fatherName.setText(rs.getString("faname"));
                        familyName.setText(rs.getString("lname"));
                        Date date = rs.getDate("birthdate");
                        if (date != null)
                        birthDate.setText(date.toString());
                        countryLocation.setText(rs.getString("country"));
                        cityVal.setText(rs.getString("city"));
                        fatherMobileVal.setText(rs.getString("famobile"));
                        nationalityVal.setText(rs.getString("nationality"));
                        HometelVal.setText(rs.getString("Hometel"));
                        addressVal.setText((rs.getString("address")));
                        if (rs.getString("Gender").equals("ذكر")) 
                            male.setSelected(true);
                        else 
                            female.setSelected(true);
                        male.setSelected(rootPaneCheckingEnabled);
                }    } catch (SQLException ex) {
                Logger.getLogger(CrudSt.class.getName()).log(Level.SEVERE, null, ex);
            }
    }
    public ResultSet getData(int id) throws Exception {
        ResultSet result =data.getStudent(id);
        return result;
    }
    public CrudSt() {
        initComponents();
        setDefaultCloseOperation(this.DISPOSE_ON_CLOSE);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        maleOrfemale = new javax.swing.ButtonGroup();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        firstName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        familyName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        fatherName = new javax.swing.JTextField();
        fileId = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        submitButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        cityVal = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        countryLocation = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        fatherMobileVal = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        addressVal = new javax.swing.JTextArea();
        nationalityVal = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        HometelVal = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        birthDate = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        deleteFile = new javax.swing.JButton();
        newRecord = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel4.setBackground(new java.awt.Color(0, 102, 204));
        jPanel4.setLayout(null);

        jLabel15.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("X");
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel15MouseExited(evt);
            }
        });
        jPanel4.add(jLabel15);
        jLabel15.setBounds(0, 10, 30, 30);

        jLabel17.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("ملف الطالب");
        jPanel4.add(jLabel17);
        jLabel17.setBounds(730, 10, 170, 40);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(0, 0, 914, 70);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("الأسم الأول");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, -1, -1));

        jLabel2.setBackground(new java.awt.Color(0, 102, 204));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("صورة الطالب");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 90, 120, -1));

        firstName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        firstName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        firstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameActionPerformed(evt);
            }
        });
        jPanel1.add(firstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, 144, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("اسم الأب ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, -1, -1));

        familyName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        familyName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        familyName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                familyNameActionPerformed(evt);
            }
        });
        jPanel1.add(familyName, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 129, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("اسم العائلة");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, -1, -1));

        fatherName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fatherName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        fatherName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fatherNameActionPerformed(evt);
            }
        });
        jPanel1.add(fatherName, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 129, 30));

        fileId.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fileId.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        fileId.setEnabled(false);
        fileId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileIdActionPerformed(evt);
            }
        });
        jPanel1.add(fileId, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 80, 129, 30));

        jButton3.setBackground(new java.awt.Color(204, 204, 204));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setText("رجوع");
        jButton3.setBorder(null);
        jButton3.setMaximumSize(new java.awt.Dimension(71, 31));
        jButton3.setMinimumSize(new java.awt.Dimension(71, 31));
        jButton3.setPreferredSize(new java.awt.Dimension(71, 31));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 410, 70, 30));

        submitButton.setBackground(new java.awt.Color(0, 102, 204));
        submitButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        submitButton.setForeground(new java.awt.Color(255, 255, 255));
        submitButton.setText("تحديث");
        submitButton.setBorder(null);
        submitButton.setVisible(false);
        submitButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });
        jPanel1.add(submitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 410, 90, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("تاريخ الميلاد");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 130, -1, -1));

        cityVal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cityVal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        cityVal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityValActionPerformed(evt);
            }
        });
        jPanel1.add(cityVal, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 127, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("بلد الإقامة");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, -1, -1));

        countryLocation.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        countryLocation.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel1.add(countryLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, 127, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("رقم جوال الأب");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, -1));

        fatherMobileVal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fatherMobileVal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel1.add(fatherMobileVal, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 127, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("العنوان");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 290, 50, -1));

        addressVal.setColumns(20);
        addressVal.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        addressVal.setLineWrap(true);
        addressVal.setRows(5);
        addressVal.setText("\n");
        addressVal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        addressVal.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane1.setViewportView(addressVal);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 300, 264, 73));

        nationalityVal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nationalityVal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel1.add(nationalityVal, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 230, 127, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("الجنسية");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 200, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("الجنس");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, -1, -1));

        maleOrfemale.add(male);
        male.setText("ذكر");
        jPanel1.add(male, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 230, -1, -1));

        maleOrfemale.add(female);
        female.setText("انثى");
        female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleActionPerformed(evt);
            }
        });
        jPanel1.add(female, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 230, -1, -1));

        HometelVal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        HometelVal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel1.add(HometelVal, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 127, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("هاتف المنزل");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, -1, -1));

        birthDate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        birthDate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel1.add(birthDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 160, 127, 30));

        jLabel12.setBackground(new java.awt.Color(0, 0, 0));
        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 0, 0));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("رقم الطالب");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 50, 80, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("المدينة");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, -1, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/studentImage.jpg"))); // NOI18N
        jLabel16.setText(".");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 120, 180, 200));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 910, 10));

        deleteFile.setBackground(new java.awt.Color(255, 0, 0));
        deleteFile.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        deleteFile.setText("حذف");
        deleteFile.setBorder(null);
        deleteFile.setMaximumSize(new java.awt.Dimension(71, 31));
        deleteFile.setMinimumSize(new java.awt.Dimension(71, 31));
        deleteFile.setPreferredSize(new java.awt.Dimension(71, 31));
        deleteFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteFileActionPerformed(evt);
            }
        });
        jPanel1.add(deleteFile, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 410, 70, 30));

        newRecord.setBackground(new java.awt.Color(0, 102, 204));
        newRecord.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        newRecord.setForeground(new java.awt.Color(255, 255, 255));
        newRecord.setText("إنشاء");
        newRecord.setBorder(null);
        newRecord.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        newRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newRecordActionPerformed(evt);
            }
        });
        jPanel1.add(newRecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 410, 90, 30));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 73, 914, 480);

        setSize(new java.awt.Dimension(930, 576));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel15MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseExited
        System.exit(0);
    }//GEN-LAST:event_jLabel15MouseExited

    private void femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_femaleActionPerformed

    private void fileIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fileIdActionPerformed

    private void fatherNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fatherNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fatherNameActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        String fname   = firstName.getText();
        String faname  = fatherName.getText();
        String famname = familyName.getText();
        String country = countryLocation.getText();
        String city    = cityVal.getText();
        String address  = addressVal.getText();
        String fatherMobile = fatherMobileVal.getText();
        String Hometel      = HometelVal.getText();
        String gender  = "";
        if (male.isSelected()) {
            gender = "male";
        }
        else {
            gender="female";
        }
        if (id > 0) {
            result = data.updateQuery("UPDATE users SET fname = '"+fname+"',faname = '"+faname+"',lname= '"+famname+"', country = '"+country+"'   , city = '"+city+"' , address = '"+address+"' , famobile = '"+fatherMobile+"'  , Hometel = '"+Hometel+"' ,Gender = '"+gender+"' WHERE sid = "+id+";");
            if (result >0) {
                JOptionPane.showMessageDialog(this,"تم التحديث بنجاح");
            }
            else {
                JOptionPane.showMessageDialog(this,result+"حدث خطا","خطا",
                    JOptionPane.ERROR_MESSAGE);
            }
        }

    }//GEN-LAST:event_submitButtonActionPerformed

    private void deleteFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteFileActionPerformed
        int dialogButton = 0;
        int dialogResult = JOptionPane.showConfirmDialog (this, "سيتم حذف الملف .. هل انت متأكد ؟","تحذير",dialogButton);
        if(dialogResult == JOptionPane.YES_OPTION){
            result = data.updateQuery("DELETE FROM users WHERE sid='"+id+"';");
            if (result >0) {
            JOptionPane.showMessageDialog(this,"تم التحديث بنجاح");
            }
            else {
            JOptionPane.showMessageDialog(this,result+"حدث خطا","خطا",
            JOptionPane.ERROR_MESSAGE);
            }
}
    }//GEN-LAST:event_deleteFileActionPerformed

    private void firstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameActionPerformed

    private void cityValActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityValActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cityValActionPerformed

    private void familyNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_familyNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_familyNameActionPerformed

    private void newRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newRecordActionPerformed
        String fname = firstName.getText();
        String faname = fatherName.getText();
        String famname = familyName.getText();
        String birth = birthDate.getText();
        String country = countryLocation.getText();
        String city    = cityVal.getText();
        String fmobile = fatherMobileVal.getText();
        String nationality = nationalityVal.getText();
        String homeTel     = HometelVal.getText();
        String address     = addressVal.getText();
        String gender  = "";
        if (male.isSelected()) {
            gender = "male";
        }
        else {
            gender="female";
        }
        boolean result = data.insertQuery("INSERT INTO users (fname,faname,lname,country,city,address,famobile,Hometel,nationality,gender,birthdate) VALUES("
                + "'"+fname+"','"+faname+"','"+famname+"','"+country+"','"+city+"','"+address+"','"+fmobile+"','"+homeTel+"','"+nationality+"','"+gender+"','"+birth+"');");
                if (!result) {
                JOptionPane.showMessageDialog(this, "تم التحديث بنجاح");
            } else {
                JOptionPane.showMessageDialog(this, "حدث خطا", "خطا",
                        JOptionPane.ERROR_MESSAGE);
            }
        
        
    }//GEN-LAST:event_newRecordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrudSt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrudSt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrudSt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrudSt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrudSt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField HometelVal;
    private javax.swing.JTextArea addressVal;
    private javax.swing.JTextField birthDate;
    private javax.swing.JTextField cityVal;
    private javax.swing.JTextField countryLocation;
    private javax.swing.JButton deleteFile;
    private javax.swing.JTextField familyName;
    private javax.swing.JTextField fatherMobileVal;
    private javax.swing.JTextField fatherName;
    private javax.swing.JRadioButton female;
    private javax.swing.JTextField fileId;
    private javax.swing.JTextField firstName;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton male;
    private javax.swing.ButtonGroup maleOrfemale;
    private javax.swing.JTextField nationalityVal;
    private javax.swing.JButton newRecord;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}
