package UI;

import dataBase.dataQuery;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.ش
 */
/**
 *
 * @author Badr-Alfwazi
 */
public class CrudCu extends javax.swing.JFrame {
    private int result=0;
    private int id = 0;
    private dataQuery data = new dataQuery();

    /**
     * Creates new form CrudSt
     *
     * @param id
     */
    public void setId(int id) {
        submitButton1.setVisible(true);
        newRecord.setVisible(false);
        this.id = id;
        ResultSet rs = data.runQuery("SELECT * from courses where Subid=" + id + ";");
        try {
        while (rs.next()) {
        courseNumber.setText(rs.getString("Subid"));
        courseName.setText(rs.getString("Subname"));
        courseTeacher.setText(rs.getString("eid"));
        maxGrade.setText(rs.getString("submark"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(CrudCu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public ResultSet getData(int id) {
        ResultSet result = data.getEmployee(id);
        return result;
    }

    public CrudCu() {
        initComponents();
        setDefaultCloseOperation(CrudCu.DISPOSE_ON_CLOSE);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        maleOrfemale = new javax.swing.ButtonGroup();
        jPanel4 = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        courseName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        maxGrade = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        courseTeacher = new javax.swing.JTextField();
        courseNumber = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        newRecord = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        deleteFile = new javax.swing.JButton();
        submitButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel4.setBackground(new java.awt.Color(0, 102, 204));
        jPanel4.setLayout(null);

        Title.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        Title.setForeground(new java.awt.Color(255, 255, 255));
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("بيانات المقرر");
        jPanel4.add(Title);
        Title.setBounds(710, 20, 190, 30);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(0, 0, 914, 70);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("اسم المقرر");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 30, -1, -1));

        courseName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        courseName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        courseName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseNameActionPerformed(evt);
            }
        });
        jPanel1.add(courseName, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 60, 144, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("رقم المدرس");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, -1, -1));

        maxGrade.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        maxGrade.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        maxGrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maxGradeActionPerformed(evt);
            }
        });
        jPanel1.add(maxGrade, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 129, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("علامة النجاح");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, -1, -1));

        courseTeacher.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        courseTeacher.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        courseTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseTeacherActionPerformed(evt);
            }
        });
        jPanel1.add(courseTeacher, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, 129, 30));

        courseNumber.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        courseNumber.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        courseNumber.setEnabled(false);
        courseNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseNumberActionPerformed(evt);
            }
        });
        jPanel1.add(courseNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 60, 129, 30));

        jButton3.setBackground(new java.awt.Color(204, 204, 204));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setText("رجوع");
        jButton3.setBorder(null);
        jButton3.setMaximumSize(new java.awt.Dimension(71, 31));
        jButton3.setMinimumSize(new java.awt.Dimension(71, 31));
        jButton3.setPreferredSize(new java.awt.Dimension(71, 31));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 130, 70, 30));

        newRecord.setBackground(new java.awt.Color(0, 102, 204));
        newRecord.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        newRecord.setForeground(new java.awt.Color(255, 255, 255));
        newRecord.setText("إنشاء");
        newRecord.setBorder(null);
        newRecord.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        newRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newRecordActionPerformed(evt);
            }
        });
        jPanel1.add(newRecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 130, 90, 30));

        jLabel12.setBackground(new java.awt.Color(0, 0, 0));
        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 0, 0));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("رقم المقرر");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 30, 80, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 910, 10));

        deleteFile.setBackground(new java.awt.Color(255, 0, 0));
        deleteFile.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        deleteFile.setText("حذف");
        deleteFile.setBorder(null);
        deleteFile.setMaximumSize(new java.awt.Dimension(71, 31));
        deleteFile.setMinimumSize(new java.awt.Dimension(71, 31));
        deleteFile.setPreferredSize(new java.awt.Dimension(71, 31));
        deleteFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteFileActionPerformed(evt);
            }
        });
        jPanel1.add(deleteFile, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, 70, 30));

        submitButton1.setBackground(new java.awt.Color(0, 102, 204));
        submitButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        submitButton1.setForeground(new java.awt.Color(255, 255, 255));
        submitButton1.setText("إرسال");
        submitButton1.setBorder(null);
        submitButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        submitButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(submitButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, 90, 30));
        submitButton1.setVisible(false);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 73, 914, 170);

        setSize(new java.awt.Dimension(928, 280));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void courseNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_courseNumberActionPerformed

    private void courseTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseTeacherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_courseTeacherActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void newRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newRecordActionPerformed
        String fname = courseName.getText();
        String faname = courseTeacher.getText();
        String famname = maxGrade.getText();
        boolean result = data.insertQuery("INSERT INTO courses (Subname , eid ,submark) VALUES ('"+fname+"',"+faname+","+famname+");");
    }//GEN-LAST:event_newRecordActionPerformed

    private void deleteFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteFileActionPerformed
        String fname = courseName.getText();
        String faname = courseTeacher.getText();
        String famname = maxGrade.getText();
        int dialogButton = 0;
        int dialogResult = JOptionPane.showConfirmDialog (this, "سيتم حذف المقرر .. هل انت متأكد ؟","تحذير",dialogButton);
        if(dialogResult == JOptionPane.YES_OPTION){ 
        result = data.updateQuery("DELETE FROM courses WHERE Subid='"+id+"';");
        if (result >0) {
            JOptionPane.showMessageDialog(this, "تم التحديث بنجاح");
        } else {
            JOptionPane.showMessageDialog(this, "حدث خطا", "خطا",
                    JOptionPane.ERROR_MESSAGE);
        }
        }
    }//GEN-LAST:event_deleteFileActionPerformed

    private void courseNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_courseNameActionPerformed

    private void maxGradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maxGradeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maxGradeActionPerformed

    private void submitButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButton1ActionPerformed
        String fname = courseName.getText();
        String faname = courseTeacher.getText();
        String famname = maxGrade.getText();
        if (id > 0) {
        System.out.println("CrudEm Update"+id);
        int result = 0;
        result = data.updateQuery("UPDATE courses SET Subname = '" + fname + "',eid = '" + faname + "',submark= '" + famname + "' WHERE Subid = "+id+";");
            if (result > 0) {
                JOptionPane.showMessageDialog(this, "تم التحديث بنجاح");
            } else {
                JOptionPane.showMessageDialog(this, "حدث خطا", "خطا",
                        JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_submitButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrudCu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrudCu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrudCu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrudCu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrudCu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Title;
    private javax.swing.JTextField courseName;
    private javax.swing.JTextField courseNumber;
    private javax.swing.JTextField courseTeacher;
    private javax.swing.JButton deleteFile;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.ButtonGroup maleOrfemale;
    private javax.swing.JTextField maxGrade;
    private javax.swing.JButton newRecord;
    private javax.swing.JButton submitButton1;
    // End of variables declaration//GEN-END:variables
}
