package UI;

import dataBase.dataQuery;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.ش
 */
/**
 *
 * @author Badr-Alfwazi
 */
public class CrudGr extends javax.swing.JFrame {

    private int id = 0;
    private dataQuery data = new dataQuery();

    /**
     * Creates new form CrudSt
     *
     * @param id
     */
    public void setId(int id) {
        this.id = id;
        ResultSet rs = data.runQuery("SELECT * from grades where Sid="+id + ";");
        ResultSet st = data.runQuery("SELECT * from users where sid=" + id + ";");
        try {
            while (st.next()) {
                courseNumber.setText(st.getString("sid"));
                courseName.setText(st.getString("fname"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(CrudGr.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            while (rs.next()) {
               courseTeacher.setText(rs.getString("Eid"));
               maxGrade2.setText(rs.getString("Oralmark"));
               maxGrade3.setText(rs.getString("Jobmark"));
               maxGrade.setText(rs.getString("Studymark"));
               maxGrade1.setText(rs.getString("Exammark"));
               maxGrade4.setText(rs.getString("resultmark"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(CrudGr.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public ResultSet getData(int id) {
        ResultSet result = data.getEmployee(id);
        return result;
    }

    public CrudGr() {
        initComponents();
        setDefaultCloseOperation(this.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        maleOrfemale = new javax.swing.ButtonGroup();
        jPanel4 = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        courseName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        maxGrade = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        courseTeacher = new javax.swing.JTextField();
        courseNumber = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        submitButton = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        deleteFile = new javax.swing.JButton();
        maxGrade1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        maxGrade2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        maxGrade3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        maxGrade4 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel4.setBackground(new java.awt.Color(0, 102, 204));
        jPanel4.setLayout(null);

        Title.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        Title.setForeground(new java.awt.Color(255, 255, 255));
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("درجات الطالب");
        jPanel4.add(Title);
        Title.setBounds(710, 20, 190, 30);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(0, 0, 914, 70);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("اسم الطالب");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 30, -1, -1));

        courseName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        courseName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        courseName.setEnabled(false);
        courseName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseNameActionPerformed(evt);
            }
        });
        jPanel1.add(courseName, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 60, 144, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("رقم المدرس");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, -1, -1));

        maxGrade.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        maxGrade.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        maxGrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maxGradeActionPerformed(evt);
            }
        });
        jPanel1.add(maxGrade, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 150, 129, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("درجة المذاكرة");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 120, -1, -1));

        courseTeacher.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        courseTeacher.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        courseTeacher.setEnabled(false);
        courseTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseTeacherActionPerformed(evt);
            }
        });
        jPanel1.add(courseTeacher, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, 129, 30));

        courseNumber.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        courseNumber.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        courseNumber.setEnabled(false);
        courseNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseNumberActionPerformed(evt);
            }
        });
        jPanel1.add(courseNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 60, 129, 30));

        jButton3.setBackground(new java.awt.Color(204, 204, 204));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setText("رجوع");
        jButton3.setBorder(null);
        jButton3.setMaximumSize(new java.awt.Dimension(71, 31));
        jButton3.setMinimumSize(new java.awt.Dimension(71, 31));
        jButton3.setPreferredSize(new java.awt.Dimension(71, 31));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 250, 70, 30));

        submitButton.setBackground(new java.awt.Color(0, 102, 204));
        submitButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        submitButton.setForeground(new java.awt.Color(255, 255, 255));
        submitButton.setText("تحديث");
        submitButton.setBorder(null);
        submitButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });
        jPanel1.add(submitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 250, 90, 30));

        jLabel12.setBackground(new java.awt.Color(0, 0, 0));
        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 0, 0));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("رقم الطالب");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 30, 80, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 910, -1));

        deleteFile.setBackground(new java.awt.Color(255, 0, 0));
        deleteFile.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        deleteFile.setText("حذف");
        deleteFile.setBorder(null);
        deleteFile.setMaximumSize(new java.awt.Dimension(71, 31));
        deleteFile.setMinimumSize(new java.awt.Dimension(71, 31));
        deleteFile.setPreferredSize(new java.awt.Dimension(71, 31));
        deleteFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteFileActionPerformed(evt);
            }
        });
        jPanel1.add(deleteFile, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, 70, 30));

        maxGrade1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        maxGrade1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        maxGrade1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maxGrade1ActionPerformed(evt);
            }
        });
        jPanel1.add(maxGrade1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 150, 140, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("درجات الإمتحان");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 120, -1, -1));

        maxGrade2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        maxGrade2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        maxGrade2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maxGrade2ActionPerformed(evt);
            }
        });
        jPanel1.add(maxGrade2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 129, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("درجة الشفهي");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, -1, -1));

        maxGrade3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        maxGrade3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        maxGrade3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maxGrade3ActionPerformed(evt);
            }
        });
        jPanel1.add(maxGrade3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 129, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("درجةالواجبات");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("نتيجة الفصل");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, -1, -1));

        maxGrade4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        maxGrade4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        maxGrade4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maxGrade4ActionPerformed(evt);
            }
        });
        jPanel1.add(maxGrade4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 129, 30));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 73, 914, 320);

        setSize(new java.awt.Dimension(928, 426));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void courseNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_courseNumberActionPerformed

    private void courseTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseTeacherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_courseTeacherActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        String userid = courseNumber.getText();
        String Oral      = maxGrade2.getText();
        String Job       = maxGrade3.getText();
        String study     =  maxGrade.getText();
        String exam      = maxGrade1.getText();
        int result;
        result = data.updateQuery("UPDATE grades SET Oralmark = '" + Oral + "',Jobmark = '" + Job + "',Studymark= '" +study+ "',Exammark= '" +exam+ "' WHERE Subid = "+id+";");
        if (result >0) {
            JOptionPane.showMessageDialog(this, "تم التحديث بنجاح");
            } else {
            JOptionPane.showMessageDialog(this, "حدث خطا", "خطا",
            JOptionPane.ERROR_MESSAGE);
            }
    }//GEN-LAST:event_submitButtonActionPerformed

    private void deleteFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteFileActionPerformed
        String fname = courseName.getText();
        String faname = courseTeacher.getText();
        String famname = maxGrade.getText();
        boolean result = false;
        try {
            result = data.insertQuery("insert INTO users (fname,faname,lname) VALUES ('" + fname + "','" + faname + "','" + famname + "')");
        } catch (Exception ex) {
            Logger.getLogger(CrudGr.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (result) {
            JOptionPane.showMessageDialog(this, "تم التحديث بنجاح");
        } else {
            JOptionPane.showMessageDialog(this, "حدث خطا", "خطا",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_deleteFileActionPerformed

    private void courseNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_courseNameActionPerformed

    private void maxGradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maxGradeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maxGradeActionPerformed

    private void maxGrade1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maxGrade1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maxGrade1ActionPerformed

    private void maxGrade2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maxGrade2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maxGrade2ActionPerformed

    private void maxGrade3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maxGrade3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maxGrade3ActionPerformed

    private void maxGrade4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maxGrade4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maxGrade4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrudGr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrudGr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrudGr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrudGr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrudGr().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Title;
    private javax.swing.JTextField courseName;
    private javax.swing.JTextField courseNumber;
    private javax.swing.JTextField courseTeacher;
    private javax.swing.JButton deleteFile;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.ButtonGroup maleOrfemale;
    private javax.swing.JTextField maxGrade;
    private javax.swing.JTextField maxGrade1;
    private javax.swing.JTextField maxGrade2;
    private javax.swing.JTextField maxGrade3;
    private javax.swing.JTextField maxGrade4;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}
